[package]
name = "kubeport"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["ws"] }
bincode = "1.3.3"
clap = { version = "4.5.11", features = ["derive", "env"] }
dashmap = "6.0.1"
flume = "0.11.0"
futures-util = "0.3.30"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.39.1", features = ["io-std", "io-util", "macros", "rt", "rt-multi-thread"] }
tokio-tungstenite = "0.23.1"
uuid7 = { version = "1.0.0", features = ["serde"] }
