[package]
name = "kubeport"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["ws"] }
clap = { version = "4.5.11", features = ["derive", "env"] }
dashmap = "6.0.1"
tokio = { version = "1.39.1", features = ["io-std", "io-util", "macros", "rt", "rt-multi-thread"] }
tokio-tungstenite = "0.23.1"
